name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-prefect-pipeline:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .  # Install the ml_pipeline module in editable mode

      - name: Run Prefect pipeline
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_WORKSPACE: ${{ secrets.PREFECT_WORKSPACE }}
        run: |
          python scripts/prefect_flow.py

  deploy-to-koyeb:
    needs: run-prefect-pipeline
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Koyeb using Dockerized CLI
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          docker run --rm \
            -e KOYEB_API_KEY=${{ secrets.KOYEB_API_KEY }} \
            koyeb/cli:latest \
            auth login --token $KOYEB_API_KEY

          docker run --rm \
            -e KOYEB_API_KEY=${{ secrets.KOYEB_API_KEY }} \
            koyeb/cli:latest \
            service deploy flask-app \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest \
            --port-mapping 5000:http \
            --regions fra \
            --env FLASK_APP=app.py \
            --env FLASK_ENV=production