name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-prefect-pipeline:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .  # Install the ml_pipeline module in editable mode

      - name: Run Prefect pipeline
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_WORKSPACE: ${{ secrets.PREFECT_WORKSPACE }}
        run: |
          python scripts/prefect_flow.py

  build-and-push-docker:
    needs: run-prefect-pipeline
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ec2p:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ec2p:latest

  deploy-to-koyeb:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Koyeb GitHub Action
        uses: ./.github/actions/koyeb-action  # Path to your Koyeb GitHub Action
        with:
          api_token: ${{ secrets.KOYEB_API_KEY }}
          github_token: ${{ github.token }}

      - name: Create Koyeb Application
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          koyeb app create ec2p || echo "Application 'flask-app' already exists."

      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          koyeb service create ec2p-service \
            --app ec2p \
            --docker ${{ secrets.DOCKER_HUB_USERNAME }}/ec2p:latest \
            --port 5000:tcp \
            --route /:5000 \
            --instance-type free \
            --env FLASK_APP=app.py \
            --env FLASK_ENV=production \
            --env PORT=5000