name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest

  deploy-to-koyeb:
    needs: build-and-push-docker
    runs-on: ubuntu-22.04
    steps:
      - name: Install Koyeb CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh

      - name: Log in to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          koyeb auth login --token $KOYEB_API_KEY

      - name: Deploy to Koyeb
        env:
          KOYEB_API_KEY: ${{ secrets.KOYEB_API_KEY }}
        run: |
          koyeb service deploy flask-app \
            --image ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app:latest \
            --port-mapping 5000:http \
            --regions fra \
            --env FLASK_APP=app.py \
            --env FLASK_ENV=production
